import { describe, it, expect, beforeEach, afterEach } from "vitest";
import { mkdir, rm, readFile, writeFile } from "node:fs/promises";
import * as path from "node:path";
import * as os from "node:os";
import { ContextStore } from "../src/context-store.js";
import { UserInputError } from "../src/types.js";

function getTmpDir(): string {
  return path.join(
    os.tmpdir(),
    `opencontext-test-${Date.now()}-${Math.random().toString(36).slice(2)}`,
  );
}

describe("Auto-Generated Context Index", () => {
  let tmpDir: string;
  let store: ContextStore;

  beforeEach(async () => {
    tmpDir = getTmpDir();
    await mkdir(tmpDir, { recursive: true });
    store = new ContextStore(tmpDir);
  });

  afterEach(async () => {
    await rm(tmpDir, { recursive: true, force: true });
  });

  describe("1. Empty directory", () => {
    it("returns empty message and does not create index.md", async () => {
      const result = await store.readContext();
      expect(result).toContain("No OpenContext topics found");

      const indexPath = path.join(tmpDir, ".opencontext", "index.md");
      await expect(readFile(indexPath, "utf8")).rejects.toThrow();
    });
  });

  describe("2. Multi-file indexing", () => {
    it("indexes multiple topics with descriptions, dates, and sizes", async () => {
      await store.saveContext("architecture", "# Architecture\n\nHigh-level system structure.");
      await store.saveContext("db-schema", "# DB Schema\n\nPostgreSQL tables and relations.");

      const result = await store.readContext();

      // Header
      expect(result).toContain("# Project Context Index");
      expect(result).toContain("AUTO-GENERATED BY OPENCONTEXT");

      // Topics listed in bold
      expect(result).toContain("**architecture**");
      expect(result).toContain("**db-schema**");

      // Filenames in backticks
      expect(result).toContain("`architecture.md`");
      expect(result).toContain("`db-schema.md`");

      // Dates (YYYY-MM-DD format)
      const today = new Date().toISOString().slice(0, 10);
      expect(result).toContain(`Updated: ${today}`);

      // Descriptions extracted from first heading
      expect(result).toContain("> Architecture");
      expect(result).toContain("> DB Schema");

      // Footer
      expect(result).toContain("call `read_context` with the topic name");
    });

    it("writes index.md to disk", async () => {
      await store.saveContext("rules", "# Rules\n\nCoding standards.");

      await store.readContext();

      const indexPath = path.join(tmpDir, ".opencontext", "index.md");
      const content = await readFile(indexPath, "utf8");
      expect(content).toContain("**rules**");
    });
  });

  describe("3. Internal file filtering", () => {
    it("does not list index.md as a topic in the index", async () => {
      const dir = path.join(tmpDir, ".opencontext");
      await mkdir(dir, { recursive: true });
      await writeFile(path.join(dir, "index.md"), "# Existing index\n\nStale content.");
      await store.saveContext("real-topic", "# Real\n\nActual content.");

      const result = await store.readContext();

      // The index should contain the real topic
      expect(result).toContain("**real-topic**");

      // The stale "Existing index" heading should not appear
      expect(result).not.toContain("Existing index");
    });

    it("does not list README.md as a topic", async () => {
      const dir = path.join(tmpDir, ".opencontext");
      await mkdir(dir, { recursive: true });
      await writeFile(path.join(dir, "README.md"), "# README\n\nUser notes.");
      await store.saveContext("my-topic", "# My Topic\n\nDetails.");

      const result = await store.readContext();

      expect(result).toContain("**my-topic**");
      expect(result).not.toContain("**README**");
    });

    it("ignores .history/ directory entries", async () => {
      const dir = path.join(tmpDir, ".opencontext");
      await mkdir(path.join(dir, ".history"), { recursive: true });
      await writeFile(path.join(dir, ".history", "old.md"), "old content");
      await store.saveContext("active", "# Active\n\nCurrent.");

      const result = await store.readContext();

      expect(result).toContain("**active**");
      expect(result).not.toContain("old.md");
    });
  });

  describe("4. Description fallback", () => {
    it("extracts description from YAML frontmatter", async () => {
      const content = "---\ndescription: REST conventions and auth schemes.\ntitle: API\n---\n\n# API Contracts\n\nDetailed content here.";
      await store.saveContext("api", content);

      const result = await store.readContext();
      expect(result).toContain("> REST conventions and auth schemes.");
    });

    it("extracts description from first heading when no frontmatter", async () => {
      await store.saveContext("arch", "# System Architecture\n\nDetails.");
      const result = await store.readContext();
      expect(result).toContain("> System Architecture");
    });

    it("truncates long paragraphs to 120 characters", async () => {
      const longParagraph = "A".repeat(150);
      await store.saveContext("long", longParagraph);

      const result = await store.readContext();
      // Should contain truncated version + ellipsis
      expect(result).toContain("A".repeat(120) + "...");
      // Should NOT contain the full 150-char string
      expect(result).not.toContain("A".repeat(150));
    });

    it("returns fallback for empty files", async () => {
      const dir = path.join(tmpDir, ".opencontext");
      await mkdir(dir, { recursive: true });
      await writeFile(path.join(dir, "empty.md"), "");

      const result = await store.readContext();
      expect(result).toContain("> No summary available.");
    });

    it("returns fallback for whitespace-only files", async () => {
      const dir = path.join(tmpDir, ".opencontext");
      await mkdir(dir, { recursive: true });
      await writeFile(path.join(dir, "blank.md"), "   \n\n  ");

      const result = await store.readContext();
      expect(result).toContain("> No summary available.");
    });

    it("extracts first paragraph line (not heading) when no heading exists", async () => {
      await store.saveContext("notes", "Just some plain text notes.\nMore lines here.");
      const result = await store.readContext();
      expect(result).toContain("> Just some plain text notes.");
    });
  });

  describe("5. Tool integration — WriteGuard blocks 'index' topic", () => {
    it("throws UserInputError when trying to save to 'index' topic", async () => {
      await expect(store.saveContext("index", "malicious content")).rejects.toThrow(
        UserInputError,
      );
    });

    it("does not create or overwrite index.md when guard rejects", async () => {
      await store.saveContext("safe-topic", "# Safe\n\nContent.");

      // Read to create index.md
      await store.readContext();
      const indexPath = path.join(tmpDir, ".opencontext", "index.md");
      const beforeContent = await readFile(indexPath, "utf8");
      expect(beforeContent).toContain("**safe-topic**");

      // Attempt to overwrite via save_context
      await expect(store.saveContext("index", "hacked")).rejects.toThrow(UserInputError);

      // index.md should be unchanged
      const afterContent = await readFile(indexPath, "utf8");
      expect(afterContent).toBe(beforeContent);
    });
  });
});
