import { readFile, writeFile } from "node:fs/promises";
import * as path from "node:path";
import { OPENCONTEXT_MCP_PACKAGE } from "../../shared/constants.js";
import { isNodeError } from "../../shared/errors.js";
import type { ConfigWriteResult } from "../../shared/types.js";

/** Filename for the Claude Code project MCP config. */
export const CLAUDE_MCP_FILENAME = ".mcp.json";

/** Shape of the Claude Code MCP server entry generated by init. */
export interface ClaudeMcpEntry {
  command: string;
  args: string[];
}

/** Current Claude Code MCP server entry. */
export function claudeMcpEntry(): ClaudeMcpEntry {
  return {
    command: "npx",
    args: ["-y", OPENCONTEXT_MCP_PACKAGE],
  };
}

function isPlainObject(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

interface ExistingJson {
  exists: boolean;
  malformed: boolean;
  parsed?: Record<string, unknown>;
}

/**
 * Reads an existing JSON config file, distinguishing "missing" from
 * "present but not parseable".
 */
async function readExistingJson(filePath: string): Promise<ExistingJson> {
  let raw: string;
  try {
    raw = await readFile(filePath, "utf8");
  } catch (error) {
    if (isNodeError(error) && error.code === "ENOENT") {
      return { exists: false, malformed: false };
    }
    throw error;
  }

  try {
    return {
      exists: true,
      malformed: false,
      parsed: JSON.parse(raw) as Record<string, unknown>,
    };
  } catch {
    return { exists: true, malformed: true };
  }
}

/** Whether an existing Claude MCP entry matches the current shape. */
function isClaudeMcpCurrent(entry: unknown): boolean {
  if (!isPlainObject(entry)) {
    return false;
  }
  const desired = claudeMcpEntry();
  const current = entry as Record<string, unknown>;
  const args = current.args;
  return (
    current.command === desired.command &&
    Array.isArray(args) &&
    args.length === desired.args.length &&
    (args as string[]).every((part, i) => part === desired.args[i])
  );
}

/**
 * Ensures the Claude Code config has a current OpenContext MCP server entry.
 * Existing configs are extended, never overwritten: all other keys and MCP
 * servers are preserved. An already-current entry is left untouched.
 * @param targetDir - Project root directory
 */
export async function upsertClaudeConfig(targetDir: string): Promise<ConfigWriteResult> {
  const filePath = path.join(targetDir, CLAUDE_MCP_FILENAME);
  const existing = await readExistingJson(filePath);

  if (existing.exists && existing.malformed) {
    return {
      status: "skipped",
      message: `${CLAUDE_MCP_FILENAME} exists but is not valid JSON — left untouched.`,
    };
  }

  const existingConfig = existing.parsed ?? {};
  const existingServers = isPlainObject(existingConfig.mcpServers)
    ? existingConfig.mcpServers
    : {};
  const current = existingServers.opencontext;

  if (current !== undefined && isClaudeMcpCurrent(current)) {
    return {
      status: "unchanged",
      message: `${CLAUDE_MCP_FILENAME} — OpenContext MCP server is up to date.`,
    };
  }

  const merged: Record<string, unknown> = { ...existingConfig };
  const servers: Record<string, unknown> = { ...existingServers };
  servers.opencontext = claudeMcpEntry();
  merged.mcpServers = servers;

  await writeFile(filePath, `${JSON.stringify(merged, null, 2)}\n`, "utf8");

  const status = existing.exists ? "updated" : "created";
  const verb = existing.exists ? "updated" : "created";
  return {
    status,
    message: `${CLAUDE_MCP_FILENAME} ${verb} — OpenContext MCP server configured.`,
  };
}