import { readFile, writeFile } from "node:fs/promises";
import * as path from "node:path";
import { OPENCONTEXT_MCP_PACKAGE } from "../../shared/constants.js";
import { isNodeError } from "../../shared/errors.js";
import type { ConfigWriteResult } from "../../shared/types.js";

/** Filename for the OpenCode project config. */
export const OPENCODE_CONFIG_FILENAME = "opencode.json";

/** JSON schema used for generated OpenCode configs. */
export const OPENCODE_CONFIG_SCHEMA = "https://opencode.ai/config.json";

/** Shape of the OpenCode MCP server entry generated by init. */
export interface OpenCodeMcpEntry {
  type: "local";
  command: string[];
  enabled: boolean;
}

/** Current OpenCode MCP server entry. */
export function openCodeMcpEntry(): OpenCodeMcpEntry {
  return {
    type: "local",
    command: ["npx", "-y", OPENCONTEXT_MCP_PACKAGE],
    enabled: true,
  };
}

function isPlainObject(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

interface ExistingJson {
  exists: boolean;
  malformed: boolean;
  parsed?: Record<string, unknown>;
}

/**
 * Reads an existing JSON config file, distinguishing "missing" from
 * "present but not parseable".
 */
async function readExistingJson(filePath: string): Promise<ExistingJson> {
  let raw: string;
  try {
    raw = await readFile(filePath, "utf8");
  } catch (error) {
    if (isNodeError(error) && error.code === "ENOENT") {
      return { exists: false, malformed: false };
    }
    throw error;
  }

  try {
    return {
      exists: true,
      malformed: false,
      parsed: JSON.parse(raw) as Record<string, unknown>,
    };
  } catch {
    return { exists: true, malformed: true };
  }
}

/** Whether an existing OpenCode MCP entry matches the current shape. */
function isOpenCodeMcpCurrent(entry: unknown): boolean {
  if (!isPlainObject(entry)) {
    return false;
  }
  const desired = openCodeMcpEntry();
  const current = entry as Record<string, unknown>;
  const command = current.command;
  return (
    current.type === desired.type &&
    Array.isArray(command) &&
    command.length === desired.command.length &&
    (command as string[]).every((part, i) => part === desired.command[i]) &&
    current.enabled !== false
  );
}

/**
 * Ensures the OpenCode config has a current OpenContext MCP server entry.
 * Existing configs are extended, never overwritten: all other keys and MCP
 * servers are preserved. An already-current entry is left untouched.
 * @param targetDir - Project root directory
 */
export async function upsertOpenCodeConfig(targetDir: string): Promise<ConfigWriteResult> {
  const filePath = path.join(targetDir, OPENCODE_CONFIG_FILENAME);
  const existing = await readExistingJson(filePath);

  if (existing.exists && existing.malformed) {
    return {
      status: "skipped",
      message: `${OPENCODE_CONFIG_FILENAME} exists but is not valid JSON — left untouched.`,
    };
  }

  const existingConfig = existing.parsed ?? {};
  const existingMcp = isPlainObject(existingConfig.mcp) ? existingConfig.mcp : {};
  const current = existingMcp.opencontext;

  if (current !== undefined && isOpenCodeMcpCurrent(current)) {
    return {
      status: "unchanged",
      message: `${OPENCODE_CONFIG_FILENAME} — OpenContext MCP server is up to date.`,
    };
  }

  // Preserve existing $schema, otherwise add the current one.
  const merged: Record<string, unknown> = {};
  if (typeof existingConfig.$schema === "string") {
    merged.$schema = existingConfig.$schema;
  } else {
    merged.$schema = OPENCODE_CONFIG_SCHEMA;
  }
  for (const [key, value] of Object.entries(existingConfig)) {
    if (key !== "$schema" && key !== "mcp") {
      merged[key] = value;
    }
  }

  const mcp: Record<string, unknown> = { ...existingMcp };
  mcp.opencontext = openCodeMcpEntry();
  merged.mcp = mcp;

  await writeFile(filePath, `${JSON.stringify(merged, null, 2)}\n`, "utf8");

  const status = existing.exists ? "updated" : "created";
  const verb = existing.exists ? "updated" : "created";
  return {
    status,
    message: `${OPENCODE_CONFIG_FILENAME} ${verb} — OpenContext MCP server configured.`,
  };
}