import { readdir, readFile, stat, writeFile } from "node:fs/promises";
import * as path from "node:path";
import { INDEX_FILENAME, STATUS_BADGES, type TopicStatus } from "../shared/constants.js";
import { isNodeError } from "../shared/errors.js";
import type { TopicFrontmatter } from "../shared/types.js";

export interface TopicIndexEntry {
  topic: string;
  filename: string;
  description: string;
  date: string;
  sizeBytes: number;
  status: TopicStatus | undefined;
  supersedes: string | undefined;
  superseded_by: string | undefined;
}

/**
 * Parses YAML frontmatter from markdown content.
 * Returns extracted fields or an empty object when no frontmatter is present.
 * Uses simple line-by-line parsing — no external YAML dependency.
 */
export function parseFrontmatter(content: string): TopicFrontmatter {
  const trimmed = content.trim();
  if (!trimmed.startsWith("---")) {
    return {};
  }

  const endIdx = trimmed.indexOf("---", 3);
  if (endIdx === -1) {
    return {};
  }

  const block = trimmed.slice(3, endIdx);
  const result: TopicFrontmatter = {};

  for (const line of block.split("\n")) {
    const trimmedLine = line.trim();
    if (!trimmedLine || trimmedLine.startsWith("#")) continue;

    const colonIdx = trimmedLine.indexOf(":");
    if (colonIdx === -1) continue;

    const key = trimmedLine.slice(0, colonIdx).trim();
    let value = trimmedLine.slice(colonIdx + 1).trim();

    // Strip surrounding quotes
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }

    if (key === "description") {
      result.description = value;
    } else if (
      key === "status" &&
      (value === "active" || value === "deprecated" || value === "superseded")
    ) {
      result.status = value;
    } else if (key === "supersedes") {
      result.supersedes = value;
    } else if (key === "superseded_by") {
      result.superseded_by = value;
    }
  }

  return result;
}

/**
 * Extracts a short description from markdown content.
 * Strategy: frontmatter description → first heading → first paragraph → fallback.
 * @param content - Raw markdown content
 * @returns Truncated description (max 120 chars)
 */
export function extractDescription(content: string): string {
  const trimmed = content.trim();
  if (!trimmed) {
    return "No summary available.";
  }

  const fm = parseFrontmatter(content);
  if (fm.description) {
    return fm.description.slice(0, 120);
  }

  const lines = trimmed.split("\n");

  // Fall back to the first heading, then the first paragraph line.
  for (const line of lines) {
    const headingMatch = line.match(/^#\s+(.+)$/);
    if (headingMatch?.[1]) {
      return headingMatch[1].slice(0, 120);
    }
  }

  for (const line of lines) {
    const stripped = line.trim();
    if (stripped && !stripped.startsWith("#")) {
      return stripped.length > 120 ? stripped.slice(0, 120) + "..." : stripped;
    }
  }

  return "No summary available.";
}

/** Formats a byte count as a compact human-readable size string. */
function formatSize(sizeBytes: number): string {
  return sizeBytes >= 1024
    ? `${(sizeBytes / 1024).toFixed(1)} KB`
    : `${sizeBytes} B`;
}

/**
 * Rebuilds the auto-generated index.md file in the context directory.
 * Scans all topic files, extracts metadata, and writes a compact index.
 * @param contextDir - Absolute path to the .opencontext directory
 * @returns The generated index markdown content ("" when no topics exist)
 */
export async function buildContextIndex(contextDir: string): Promise<string> {
  let entries;
  try {
    entries = await readdir(contextDir, { withFileTypes: true });
  } catch (error) {
    if (isNodeError(error) && error.code === "ENOENT") {
      return "";
    }
    throw error;
  }

  const topicFiles = entries
    .filter(
      (entry) =>
        entry.isFile() &&
        entry.name.endsWith(".md") &&
        entry.name !== INDEX_FILENAME &&
        entry.name !== "README.md",
    )
    .sort((a, b) => a.name.localeCompare(b.name));

  if (topicFiles.length === 0) {
    return "";
  }

  const topicEntries: TopicIndexEntry[] = [];

  for (const entry of topicFiles) {
    const filePath = path.join(contextDir, entry.name);
    const content = await readFile(filePath, "utf8");
    const fileStat = await stat(filePath);
    const topic = entry.name.slice(0, -".md".length);
    const fm = parseFrontmatter(content);

    topicEntries.push({
      topic,
      filename: entry.name,
      description: extractDescription(content),
      date: fileStat.mtime.toISOString().slice(0, 10),
      sizeBytes: Buffer.byteLength(content, "utf8"),
      status: fm.status,
      supersedes: fm.supersedes,
      superseded_by: fm.superseded_by,
    });
  }

  const lines: string[] = [
    "# Project Context Index",
    "<!-- AUTO-GENERATED BY OPENCONTEXT - DO NOT EDIT MANUALLY -->",
    "",
    "Available context topics in this project:",
    "",
  ];

  for (const t of topicEntries) {
    const badge = t.status && t.status !== "active"
      ? ` ${STATUS_BADGES.get(t.status) ?? `[${t.status.toUpperCase()}]`}`
      : "";
    const supersedesNote = t.supersedes
      ? ` (supersedes: \`${t.supersedes}\`)`
      : "";
    const supersededByNote = t.superseded_by
      ? ` (superseded by: \`${t.superseded_by}\`)`
      : "";
    lines.push(`- **${t.topic}**${badge} (\`${t.filename}\`) - Updated: ${t.date} (${formatSize(t.sizeBytes)})${supersedesNote}${supersededByNote}`);
    lines.push(`  > ${t.description}`);
  }

  lines.push("");
  lines.push("---");
  lines.push("*To read a specific context topic, call `read_context` with the topic name.*");
  lines.push("");
  lines.push("*OpenContext is open-source. Consider starring on [GitHub](https://github.com/slxca/opencontext).*");

  const indexContent = lines.join("\n");
  const indexPath = path.join(contextDir, INDEX_FILENAME);
  await writeFile(indexPath, indexContent, "utf8");

  return indexContent;
}